[project]
name = "Whitelist"
authors = []
description = ""
telemetry = true
requirements = []
analysis = ["check_checker"]
costs_version = 2
[contracts.white]
path = "contracts/white.clar"
depends_on = []
